import React, { useState } from "react";
import "./Homepage.css";

/**
 * Homepage
 * Auto-generated by Design-to-Code AI (mock fallback).
 * Description: Generate a responsive React home page 
 */

interface HomepageProps {
  title?: string;
  subtitle?: string;
  onAction?: () => void;
}

const Homepage: React.FC<HomepageProps> = ({
  title = "Dashboard",
  subtitle = "Welcome back!",
  onAction,
}) => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <div className="homepage-wrapper">
      <aside className="homepage-sidebar">
        <div className="sidebar-logo">
          <span className="logo-text">DesignApp</span>
        </div>
        <nav className="sidebar-nav">
          {["Overview", "Analytics", "Projects", "Settings"].map((item) => (
            <a key={item} href="#" className="nav-item">{item}</a>
          ))}
        </nav>
      </aside>
      <main className="homepage-main">
        <header className="homepage-header">
          <h1>{title}</h1>
          <p>{subtitle}</p>
          <button className="btn btn-primary" onClick={onAction}>
            + New Project
          </button>
        </header>
      </main>
    </div>
  );
};

export default Homepage;
